# Generated by Django 4.2.5 on 2023-10-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('available_in_hours', 'Available in hours'), ('unavailable', 'Unavailable'), ('holiday', 'Holiday'), ('sick', 'Sick'), ('unpaid', 'Unpaid'), ('other', 'Other')], max_length=20),
        ),
    ]
