# Generated by Django 4.2.4 on 2023-10-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_availability_employee_delete_dostepnosc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='availability_hours',
        ),
        migrations.AddField(
            model_name='availability',
            name='availability_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='availability_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='availability',
            field=models.CharField(choices=[('Niedostepny', 'Niedostepny'), ('Dostepny', 'Dostepny'), ('Godziny', 'Dostepny w godzinach')], max_length=20),
        ),
    ]
