# Generated by Django 4.2.5 on 2023-10-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_availability_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='surename',
            new_name='surname',
        ),
    ]
