# Generated by Django 4.2.4 on 2023-10-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_rename_surename_employee_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='may_be_extended',
            field=models.BooleanField(default=False),
        ),
    ]
