# Generated by Django 4.2.4 on 2023-10-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231013_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='in_organisation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_admin',
        ),
    ]
