# Generated by Django 4.2.4 on 2023-10-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_name_userprofile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surename',
        ),
    ]
