# Generated by Django 4.2.4 on 2023-10-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_userprofile_name_remove_userprofile_surename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='example@example.com', max_length=100),
            preserve_default=False,
        ),
    ]
