# Generated by Django 4.2.5 on 2023-10-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231013_1322'),
        ('organisation', '0002_auto_20231013_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='admins',
            field=models.ManyToManyField(related_name='admins', to='core.userprofile'),
        ),
    ]
