# Generated by Django 4.2.4 on 2023-10-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_organisation_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
