# Generated by Django 4.2.4 on 2023-10-15 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_remove_invitation_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='organisation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation'),
            preserve_default=False,
        ),
    ]
