# Generated by Django 4.2.4 on 2023-10-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0008_invitation_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expires',
            field=models.DateTimeField(default="2023-10-15 11:10"),
            preserve_default=False,
        ),
    ]
